// This file defines custom error types for the binary options trading application,
// specifically designed to be easily convertible to Python exceptions.
// It leverages the `thiserror` crate for ergonomic error declaration and
// `pyo3` for seamless integration with Python's error handling mechanism.

// Import `BinaryOptionsToolsError` from the core `binary_options_tools` crate.
// This represents general errors originating from the underlying Rust trading logic.
use binary_options_tools::{
    error::BinaryOptionsToolsError,
    // Import `PocketOptionError` which specifically handles errors related to
    // the Pocket Option trading platform's API or logic.
    pocketoption::error::PocketOptionError,
};
// Import `PyValueError` from `pyo3` to represent a generic Python `ValueError`.
// This is used to convert Rust errors into a recognizable Python exception type.
use pyo3::{exceptions::PyValueError, PyErr};
// Import the `Error` trait from the `thiserror` crate. This macro allows
// for easy implementation of the `std::error::Error` trait, providing
// a convenient way to define custom error types with descriptive messages.
use thiserror::Error;
// Import `Uuid` for handling universally unique identifiers, particularly
// in error cases where a trade might not be found by its ID.
use uuid::Uuid;

/// `BinaryErrorPy` is an enum that consolidates all possible error types
/// that can occur within the Rust binary options trading logic, making them
/// consumable by Python.
///
/// `#[derive(Error, Debug)]` automatically implements the `std::error::Error`
/// and `std::fmt::Debug` traits, which are essential for error handling
/// and debugging. `#[error(...)]` attribute from `thiserror` defines
/// the display format for each error variant.
#[derive(Error, Debug)]
pub enum BinaryErrorPy {
    /// `BinaryOptionsError` wraps general errors from the `binary_options_tools` crate.
    /// `#[from]` enables automatic conversion from `BinaryOptionsToolsError` into this variant,
    /// simplifying error propagation.
    #[error("BinaryOptionsError, {0}")]
    BinaryOptionsError(#[from] BinaryOptionsToolsError),
    /// `PocketOptionError` wraps errors specific to the Pocket Option platform.
    /// `#[from]` allows direct conversion from `PocketOptionError`.
    #[error("PocketOptionError, {0}")]
    PocketOptionError(#[from] PocketOptionError),
    /// `Uninitialized` indicates that a component or dependency was used before it was properly
    /// initialized, often due to a missing setup step.
    #[error("Uninitialized, {0}")]
    Uninitialized(String),
    /// `DeserializingError` signifies a failure during the deserialization of data,
    /// typically from JSON, using `serde_json`.
    /// `#[from]` allows automatic conversion from `serde_json::Error`.
    #[error("Error descerializing data, {0}")]
    DeserializingError(#[from] serde_json::Error),
    /// `UuidParsingError` occurs when attempting to parse an invalid UUID string.
    /// `#[from]` allows automatic conversion from `uuid::Error`.
    #[error("UUID parsing error, {0}")]
    UuidParsingError(#[from] uuid::Error),
    /// `TradeNotFound` is specifically used when a requested trade cannot be located
    /// using its unique identifier (UUID).
    #[error("Trade not found, haven't found trade for id '{0}'")]
    TradeNotFound(Uuid),
    /// `NotAllowed` indicates that a particular operation was attempted but is not permitted
    /// under the current conditions or permissions.
    #[error("Operation not allowed")]
    NotAllowed(String),
    /// `InvalidRegexError` occurs when a provided regular expression pattern is malformed or invalid.
    /// `#[from]` allows automatic conversion from `regex::Error`.
    #[error("Invalid Regex pattern, {0}")]
    InvalidRegexError(#[from] regex::Error),
}

/// Implements the `From` trait to convert `BinaryErrorPy` into `pyo3::PyErr`.
/// This is crucial for exposing Rust errors as Python exceptions.
///
/// When a `BinaryErrorPy` occurs in Rust code called from Python, this implementation
/// ensures that a `PyValueError` is raised in Python, with the error message
/// derived from the `BinaryErrorPy`'s `to_string()` representation.
impl From<BinaryErrorPy> for PyErr {
    /// Converts a `BinaryErrorPy` enum variant into a `PyErr` (Python exception).
    /// The `PyValueError` is chosen as a general-purpose error type for Python.
    /// The error message is generated by calling `to_string()` on the `BinaryErrorPy` variant,
    /// which leverages the `#[error(...)]` attributes defined in the enum.
    fn from(value: BinaryErrorPy) -> Self {
        PyValueError::new_err(value.to_string())
    }
}

/// `BinaryResultPy` is a type alias for `Result<T, BinaryErrorPy>`.
/// This simplifies the return type signatures for functions that might
/// encounter `BinaryErrorPy` errors, making the code more concise and readable.
/// It indicates that a function can either return a successful value `T`
/// or a `BinaryErrorPy` error.
pub type BinaryResultPy<T> = Result<T, BinaryErrorPy>;